### ISSUE TITLE
Problem With Some Mods

### ISSUE THREAD

**Issue by xalamenders** [MartyrPher/SMAPI-Android-Installer#69]
I have problem with some mods

"Everlasting Baits and Unbreakable Tackles" and "SpaceCore"

Tried to inform the author on their nexus mod post, but they suggested to inform here for SMAPI based error.

My phone Honor 10 Lite android 9.

Here the log...
https://smapi.io/log/e0100e40c6e94b74917a081517ce0aa0

**Comment by MartyrPher** [comment]
Everlasting Baits should be fixed in 3.2.0.3.

The author of SpaceCore is releasing an update for Android support.

**Comment by xalamenders** [comment]
Thanks for the update, but it's seems the error still occurred for the bait.

New log:
https://smapi.io/log/2eb441d03bc24a7ba90cb5795ae7e78f
